config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "products#index"
  get "/delete", to: "products#delete"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
   belongs_to :user

   validates :product_name, :price, presence: true
  

end

app/models/user.rb
class User < ApplicationRecord
  has_many :products
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         enum role: [:admin, :merchant]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  def delete
    @products = Product.all
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:product_name, :price, :description)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    def new
        super
    end
    
    def create
       @user = User.new(user_params)
       if @user.save
          redirect_to root_path
       else
         render :new
       end
    end
    private
    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation, :role)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestingAssignment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    
       <%= render "menubar/menu" %>
        
    <%= yield %>
  </body>
</html>

app/views/menubar/_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<%= link_to "Products", root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse " id="navbarSupportedContent">
 
    <ul class="navbar-nav me-auto">
      <% if current_user %>
             <li class="nav-item">
                <%= button_to "Logout", destroy_user_session_path, class:"nav-link btn btn-success", method: :delete %>
            </li>

            <li class="nav-item">
                <%= link_to "Products", products_path, class:"nav-link" %>
            </li>

            <% if current_user.role == "admin" %>
                    <li class="nav-item">
                        <%= link_to "New product", new_product_path, class:"nav-link" %>
                    </li>

                     <li class="nav-item">
                        <%= link_to "Delete", "/delete", class:"nav-link" %>
                    </li>

            <% end %>
        <% else %>
            <li class="nav-item">
              <%= link_to "Login", user_session_path, class:"nav-link" %>
            </li>

            <li class="nav-item">
                <%= link_to "Signup", new_user_registration_path, class:"nav-link" %>
            </li>

             

      <% end %>
    </ul>
  </div>
</nav>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="row justify-content-center mt-4">
   <div class="col-lg-3">
        <div class="form-group">
              <div>
                <%= form.label :product_name, style: "display: block" %>
                <%= form.text_field :product_name, class:"form-control" %>
              </div>
        </div>
   </div>
</div>
  
  <div class="row justify-content-center mt-4">
   <div class="col-lg-3">
        <div class="form-group">
              <div>
                <%= form.label :price, style: "display: block" %>
                <%= form.number_field :price, class:"form-control" %>
              </div>
        </div>
   </div>
</div>

<div class="row justify-content-center mt-4">
   <div class="col-lg-3">
        <div class="form-group">
              <div>
                <%= form.label :description, style: "display: block" %>
                <%= form.text_field :description, class:"form-control" %>
              </div>
        </div>
   </div>
</div>

<div class="row justify-content-center mt-4">
    <div class="col-lg-3">
          <div>
            <%= form.submit class:"btn btn-success" %>
          </div>
    </div>
</div>

<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Product name:</strong>
    <%= product.product_name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

</div>

app/views/products/delete.html.erb
<table class="table">

  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Product Name</th>
      <th scope="col">Price</th>
      <th scope="col">Description</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
  <% @products.each do |product| %>
    <tr>
      <th scope="row"><%= product.id %></th>
      <td><%= product.product_name %></td>
      <td><%= product.price %></td>
      <td><%= product.description %></td>
        <td><%= button_to "Delete", product_path(product.id), method: :delete, class:"btn btn-success" %></td>
    </tr>
   <% end %>
  </tbody>
</table>

app/views/products/edit.html.erb
<h1 class="text-center m-4">Editing product</h1>

<%= render "form", product: @product %>

<br>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="text-center">Products</h1>

<table class="table">

  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Product Name</th>
      <th scope="col">Price</th>
      <th scope="col">Description</th>
      <th scope="col">Show</th>
      <th scope="col">Edit</th>
    </tr>
  </thead>
  <tbody>
  <% @products.each do |product| %>
    <tr>
      <th scope="row"><%= product.id %></th>
      <td><%= product.product_name %></td>
      <td><%= product.price %></td>
      <td><%= product.description %></td>
      <td><%= link_to "Show", product_path(product.id), class:"btn btn-success" %></td>
       <td><%= link_to "Edit", edit_product_path(product.id), class:"btn btn-success" %></td>
    </tr>
   <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<h1 class="text-center m-4">New product</h1>

<%= render "form", product: @product %>

<br>

<div class="row justify-content-center">
  <div class="col-lg-3">
      <%= link_to "Back to products", products_path, class:"btn btn-info" %>
  </div>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="row justify-content-center mt-4">
   <div class="col-lg-2">
        <p>Product Name</p>
   </div>

   <div class="col-lg-2">
         <%= @product.product_name %>
   </div>
</div>

<div class="row justify-content-center mt-4">
   <div class="col-lg-2">
        <p>Price</p>
   </div>

   <div class="col-lg-2">
         <%= @product.price %>
   </div>
</div>

<div class="row justify-content-center mt-4">
   <div class="col-lg-2">
        <p>Description</p>
   </div>

   <div class="col-lg-2">
         <%= @product.description %>
   </div>
</div>

<div class="row justify-content-center mt-4">
   <div class="col-lg-2">
         <%= link_to "Back To Home", products_path, class:"btn btn-primary m-4" %>
   </div>
 
</div>